# Generated by Django 4.0.4 on 2022-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Manga', 'Manga'), ('Romantic', 'Romantic'), ('Action', 'Action')], max_length=100, null=True),
        ),
    ]
